# Generated by Django 3.2.6 on 2021-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Events_id', models.CharField(max_length=12)),
                ('Event_Name', models.CharField(max_length=12)),
                ('Date_and_time', models.DateTimeField(max_length=12)),
                ('Event_planner', models.CharField(max_length=12)),
                ('Event_duration', models.DurationField()),
                ('Event_participants', models.TextField()),
                ('Events_approved_by', models.CharField(max_length=12)),
            ],
        ),
    ]
