# Generated by Django 3.2.6 on 2021-08-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calender',
            name='Event_duration',
        ),
        migrations.AlterField(
            model_name='calender',
            name='Date_and_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='Event_participants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
