# Generated by Django 3.2.6 on 2021-08-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=12)),
                ('Date_started', models.DateField()),
                ('Syllabus', models.TextField()),
                ('Course_id', models.CharField(max_length=12)),
                ('Time_in_hours', models.DurationField()),
                ('Course_code', models.CharField(max_length=12)),
                ('Course_duration', models.CharField(max_length=12)),
            ],
        ),
    ]
