# Generated by Django 3.2.6 on 2021-08-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=12)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField(max_length=10)),
                ('Languages', models.TextField(blank=True, null=True)),
                ('Training_day', models.CharField(max_length=12)),
                ('Email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('Date_joined', models.DateField(blank=True, null=True)),
                ('Profile', models.ImageField(upload_to='')),
                ('Bio', models.TextField(blank=True, null=True)),
                ('Contract', models.FileField(upload_to='')),
                ('Date_hired', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
