# Generated by Django 3.2.6 on 2021-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='medical_report',
            new_name='Contract',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='profile',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='county',
            new_name='Training_day',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='date_of_enrollment',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='language',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='student_id',
        ),
        migrations.AddField(
            model_name='trainer',
            name='Bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Date_hired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Languages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
