# Generated by Django 2.2.12 on 2021-09-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='Profile',
        ),
        migrations.AddField(
            model_name='trainer',
            name='profile',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
